# Generated by Django 4.2.4 on 2023-09-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0017_remove_like_post_remove_like_user_remove_post_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=6)),
                ("nationality", models.TextField()),
            ],
        ),
    ]
